// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TblUser struct {
	Uid       int32
	Username  string
	Password  string
	IsAdmin   pgtype.Bool
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
